version: '3'

services:

    qconig-admin:
        image: deepdown/qconfig-quick-start:admin
        container_name: qconig-admin
        environment:
            SLEEP_SECOND: 40
        depends_on: 
            - qconfig-server
        ports: 
            - "8083:8083"
        links: 
            - qconfig_mysql
            - qconfig-server
        entrypoint: /usr/local/tomcat/entrypoint.sh -d qconfig-server:8080 -c 'sh /usr/local/tomcat/bin/startup.sh';

    qconfig-server:
        image: deepdown/qconfig-quick-start:server
        container_name: qconfig-server
        depends_on: 
            - qconfig_mysql
        environment:
            SLEEP_SECOND: 5
        ports:  
            - "8080:8080"
            # - "5005:5005"
        expose: 
            - "8080"
        links: 
            - qconfig_mysql

        entrypoint: /usr/local/tomcat/entrypoint.sh -d qconfig_mysql:3306 -c 'sh /usr/local/tomcat/bin/catalina.sh run';

    qconfig_mysql:
        image: mysql/mysql-server:5.7
        container_name: qconfig_mysql
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment: 
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            TZ: Asia/Shanghai
        ports:
            - "3306:3306"

