apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: qconfig-server-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qconfig-server
  template:
    metadata:
      labels:
        app: qconfig-server
    spec:
      containers:
        - name: qconfig-server
          image: okracode/qconfig-quick-start:server
          ports:
          - containerPort: 8080
          env:
          - name: SLEEP_SECOND
            value: "5"
          command: ["/usr/local/tomcat/entrypoint.sh", "-d", "49.234.211.155:3306", "-c", "sh /usr/local/tomcat/bin/catalina.sh run;"]