apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: qconig-admin-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qconig-admin
  template:
    metadata:
      labels:
        app: qconig-admin
    spec:
      containers:
        - name: qconig-admin
          image: deepdown/qconfig-quick-start:admin
          ports:
          - containerPort: 8083
          env:
          - name: SLEEP_SECOND
            value: "40"
          command: [/usr/local/tomcat/entrypoint.sh -d localhost:8080 -c 'sh /usr/local/tomcat/bin/startup.sh';]